version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: sonigotchi-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sonigotchi
    ports:
      - "10002:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
